### ISSUE TITLE
Allow changing wind speed unit

### ISSUE THREAD

**Issue by BrainStone** [aukedejong/lovelace-windrose-card#3]
Hey, so I noticed that you implemented the beaufort scale based on the assumption that the value is in m/s

However some sensors may provide that in a different unit. It would be awesome if this was configurable.  
I think these units should be supported:
- m/s (current unit)
- kmh (km/h)
- mph (mi/h)
- knots (kn)
- ft/s

**Comment by aukedejong** [comment]
Release version 0.3.0
Added support for multiple input and output windspeed units.

This is still work in progress, if you encounter bugs, please open an issue here.

**Comment by BrainStone** [comment]
I get this error:

```
Uncaught (in promise) Error: Speed is not in a speedrange: NaN unit: bft
    getRangeFunction https://home-assistant.example.com/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696030:279
    addDataPoint https://home-assistant.example.com/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696030:940
    updateWindData https://home-assistant.example.com/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696030:1238
[windrose-card.js:279:19](https://home-assistant.example.comhacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696030)
    updateWindData https://home-assistant.example.com/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696030:1238
```

**Comment by aukedejong** [comment]
Looks like your windspeed entity state is not a number. (NaN)
Can you tell me the state of the sensor? Is it sometimes not a number?

**Comment by BrainStone** [comment]
```jinja
{{ states.sensor.outside_windspeed.state }}
``` 
returns `15.5` at the moment for me.

I'm not sure if it ever would be not a number. I changed nothing related to it. I only updated the windrose card to 0.3.0, which caused that error to appear.

**Comment by aukedejong** [comment]
Support for multiple speed units had quit an impact on the code. I did some tests and could only reproduce this when the speed is not a number.

Release version 0.3.1
Added checks if speed really is a number and if so, don't crash but ignore that measurement.
Also added logging details in the console when this happens.

Could you try again let me know if the console log can give us some more info?

**Comment by BrainStone** [comment]
Looks like you forgot the actual js file in the 0.3.1 release

**Comment by aukedejong** [comment]
I forgot sorry, JS file added.

**Comment by BrainStone** [comment]
```
Uncaught (in promise) Error: Speed is not in a speedrange: NaN unit: bft
    getRangeFunction https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031:251
    addDataPoint https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031:805
    updateWindData https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031:1244
```

**Comment by aukedejong** [comment]
Can you also add the console log here?  All what's logged after an browser refresh.  Thanks.

**Comment by BrainStone** [comment]
Whoops. Sorry completely missed the stuff before

```
WINROSE-CARD   Version 0.3.1 [windrose-card.js:1126:9](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
setConfig():  
Object { type: "custom:windrose-card", title: "Windverteilung", hours_to_show: 168, max_width: 400, refresh_interval: 300, windspeed_bar_location: "bottom", wind_direction_entity: "sensor.aussen_windrichtung", input_speed_unit: "kph", windspeed_entities: (1) […], direction_compensation: 0, … }
​
cardinal_direction_letters: "NESW"
​
direction_compensation: 0
​
hours_to_show: 168
​
input_speed_unit: "kph"
​
max_width: 400
​
refresh_interval: 300
​
title: "Windverteilung"
​
type: "custom:windrose-card"
​
wind_direction_entity: "sensor.aussen_windrichtung"
​
windspeed_bar_location: "bottom"
​
windspeed_entities: Array [ {…} ]
​
<prototype>: Object { … }
[windrose-card.js:1210:17](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
AUTO-ENTITIES 1.12.1 IS INSTALLED [auto-entities.js:172:7850](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-auto-entities/auto-entities.js?hacstag=1677445841121)
getCardSize() [windrose-card.js:1219:17](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
Loop start [windrose-card.js:1184:17](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
connectedCallBack() [windrose-card.js:1201:17](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
render() [windrose-card.js:1161:17](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
firstUpdated() [windrose-card.js:1174:17](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
initWindRoseObjects() [windrose-card.js:1223:17](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
updateWindData() [windrose-card.js:1237:17](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
No matching speed found for direction 238.0 at timestamp 1675099780.257888 [windrose-card.js:436:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
No matching speed found for direction 227.9 at timestamp 1675118980.750708 [windrose-card.js:436:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
No matching speed found for direction 237.8 at timestamp 1675130504.005202 [windrose-card.js:436:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
No matching speed found for direction 244.0 at timestamp 1675134344.696408 [windrose-card.js:436:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
No matching speed found for direction 236.8 at timestamp 1675211147.802968 [windrose-card.js:436:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
No matching speed found for direction 238.7 at timestamp 1675218827.751813 [windrose-card.js:436:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
No matching speed found for direction 231.7 at timestamp 1675281971.456238 [windrose-card.js:436:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
No matching speed found for direction 228.9 at timestamp 1675297331.443356 [windrose-card.js:436:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
No matching speed found for direction 232.4 at timestamp 1675308851.492374 [windrose-card.js:436:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
No matching speed found for direction 233.6 at timestamp 1675366756.580894 [windrose-card.js:436:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
No matching speed found for direction 227.4 at timestamp 1675402756.600211 [windrose-card.js:436:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
No matching speed found for direction 246.4 at timestamp 1675449155.49305 [windrose-card.js:436:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
No matching speed found for direction 248.8 at timestamp 1675452515.450584 [windrose-card.js:436:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
No matching speed found for direction 319.3 at timestamp 1675489477.442495 [windrose-card.js:436:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
No matching speed found for direction 12.0 at timestamp 1675499557.434617 [windrose-card.js:436:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
No matching speed found for direction 102.6 at timestamp 1675556683.479422 [windrose-card.js:436:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
No matching speed found for direction 230.6 at timestamp 1675566763.418835 [windrose-card.js:436:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
No matching speed found for direction 29.4 at timestamp 1675633992.760145 [windrose-card.js:436:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
No matching speed found for direction 52.5 at timestamp 1675647220.782841 [windrose-card.js:436:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
No matching speed found for direction 53.1 at timestamp 1675658380.790131 [windrose-card.js:436:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
Uncaught (in promise) Error: Speed is not in a speedrange: NaN unit: bft
    getRangeFunction https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031:251
    addDataPoint https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031:805
    updateWindData https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031:1244
[windrose-card.js:251:19](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031)
    updateWindData https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696031:1244
```

**Comment by aukedejong** [comment]
Nice, this helps. I think it has to do with the 'No matching speed..' messages.
This means there are winddirection measurements without a corresponding windspeed measurement. The 2 measurements should be within 2 seconds of each other. There is possibly a bug in that part of the code.  I'll investigate this evening.

Maybe the 2 seconds should be configurable.

**Comment by BrainStone** [comment]
Yeah that might help

**Comment by aukedejong** [comment]
v0.3.2 released.
Fixed the numeric check. Number.isNaN was working as I expected.

I hope you'll get a log message telling us what value is not numeric.

**Comment by aukedejong** [comment]
And v0.4.0 released
Added a configuration option to config the allowed time difference between a direction and speed measurement.

**Comment by BrainStone** [comment]
Interesting... I saw the windrose but without the bar. After reloading the page that was gone again.

And here's the log after it was gone again.
```
WINROSE-CARD   Version 0.4.0 [windrose-card.js:1140:9](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
setConfig():  
Object { type: "custom:windrose-card", title: "Windverteilung", hours_to_show: 168, max_width: 400, refresh_interval: 300, direction_speed_time_diff: 5, windspeed_bar_location: "bottom", wind_direction_entity: "sensor.aussen_windrichtung", input_speed_unit: "kph", windspeed_entities: (1) […], … }
​
cardinal_direction_letters: "NESW"
​
direction_compensation: 0
​
direction_speed_time_diff: 5
​
hours_to_show: 168
​
input_speed_unit: "kph"
​
max_width: 400
​
refresh_interval: 300
​
title: "Windverteilung"
​
type: "custom:windrose-card"
​
wind_direction_entity: "sensor.aussen_windrichtung"
​
windspeed_bar_location: "bottom"
​
windspeed_entities: Array [ {…} ]
​​
0: Object { entity: "sensor.aussen_windgeschwindigkeit", name: "Windgeschwindigkeit" }
​​​
entity: "sensor.aussen_windgeschwindigkeit"
​​​
name: "Windgeschwindigkeit"
​​​
<prototype>: Object { … }
​​
length: 1
​​
<prototype>: Array []
​
<prototype>: Object { … }
[windrose-card.js:1224:17](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
AUTO-ENTITIES 1.12.1 IS INSTALLED [auto-entities.js:172:7850](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-auto-entities/auto-entities.js?hacstag=1677445841121)
getCardSize() [windrose-card.js:1233:17](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
Loop start [windrose-card.js:1198:17](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
connectedCallBack() [windrose-card.js:1215:17](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
render() [windrose-card.js:1175:17](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
firstUpdated() [windrose-card.js:1188:17](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
initWindRoseObjects() [windrose-card.js:1237:17](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
updateWindData() [windrose-card.js:1251:17](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 227.9 at timestamp 1675118980.750708 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 237.8 at timestamp 1675130504.005202 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 244.0 at timestamp 1675134344.696408 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 236.8 at timestamp 1675211147.802968 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 238.7 at timestamp 1675218827.751813 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
Speed unknown at timestamp 1675243559.241316 is not a number. [windrose-card.js:251:29](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 231.7 at timestamp 1675281971.456238 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 228.9 at timestamp 1675297331.443356 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 232.4 at timestamp 1675308851.492374 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
Speed unknown at timestamp 1675330750.704627 is not a number. [windrose-card.js:251:29](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 233.6 at timestamp 1675366756.580894 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 227.4 at timestamp 1675402756.600211 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
Speed unknown at timestamp 1675418913.640622 is not a number. [windrose-card.js:251:29](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 246.4 at timestamp 1675449155.49305 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 248.8 at timestamp 1675452515.450584 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 319.3 at timestamp 1675489477.442495 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 12.0 at timestamp 1675499557.434617 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 102.6 at timestamp 1675556683.479422 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 230.6 at timestamp 1675566763.418835 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
Speed unknown at timestamp 1675617012.216865 is not a number. [windrose-card.js:251:29](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
Speed unknown at timestamp 1675618992.218751 is not a number. [windrose-card.js:251:29](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
Speed unknown at timestamp 1675619110.529481 is not a number. [windrose-card.js:251:29](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 29.4 at timestamp 1675633992.760145 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
Speed unknown at timestamp 1675643499.019375 is not a number. [windrose-card.js:251:29](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 52.5 at timestamp 1675647220.782841 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 53.1 at timestamp 1675658380.790131 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 46.0 at timestamp 1675688140.783597 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 11.8 at timestamp 1675703020.821058 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
No matching speed found for direction 23.9 at timestamp 1675706740.765462 [windrose-card.js:258:25](https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040)
Uncaught (in promise) Error: Speed is not in a speedrange: NaN unit: bft
    getRangeFunction https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040:299
    calculateSpeedRangePercentages https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040:451
    calculate https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040:444
    updateWindData https://home-assistant.brainbox.project-creative.net/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=591270696040:1265
```
    
When it drew the windrose without the graph there was something about missing something related to the bar. I'm sorry I didn't catch that log.

**Comment by aukedejong** [comment]
Looks like your speed entity sometimes has the state 'unknown'. 
`Speed unknown at timestamp 1675330750.704627 is not a number.`

But there is still a bug. The card should ignore these values, but still crashes because of a NaN value.
Need to look into that.

**Comment by aukedejong** [comment]
v0.4.1 released

Found the bug, NaN values should now be filtered correctly.

**Comment by BrainStone** [comment]
![Screenshot_20230207_190310](https://user-images.githubusercontent.com/4106544/217328633-c599ed21-60d8-44d3-a1c6-9a9ec6e26bf2.png)

Seems to work. Though is it intended that the percentages show on the bar?

**Comment by aukedejong** [comment]
Build it that way. How would you like it?
I'm not a designer, just a programmer. I'm open for ideas.

Did you also try another output unit?

**Comment by BrainStone** [comment]
It's fine. It just looks a bit odd compared to before. I'd like it if it was configurable.  
Anyways the issue is fixed.

Also I did not try other units.
